### PR TITLE
feat: implement create file and prettify

### LINKED ISSUE #2: Create a file
As a user,
I want to create a file,
so I can re-use it later.

- [x] Create a file with content
- [x] Prettify .json

### PR DESCRIPTION
**Pull request by konrascher3**
Please review my latest feature.

closes #2

### CODE REVIEW

**Review by doemser — APPROVED** [review]
looks good, but not great :see_no_evil:

**Comment by konrascher3** [comment]
(ง ͠° ͟ل͜ ͡°)ง

**Comment by haskamp** [comment]
looks better than mine ;)

**Review by haskamp — COMMENTED** [review]
too late to push merge button

**Comment by doemser** [comment]
@haskamp you shouldnt be merging in someone elses project anyway 🙈

**Comment by haskamp** [comment]
image

**Comment by konrascher3** [comment]
Leute, das ist ein pull-threat und nicht reddit

**Comment by doemser** [comment]
psst..

**Pull request merged**
